### PR TITLE
Updated Domain

### PR DESCRIPTION
**Pull request by OshekharO**

### CODE REVIEW

**Comment by BeamlakAschalew** [comment]
Doesn't 2embed.org have ads? Like overlay and video ads

**Comment by OshekharO** [comment]
> Doesn't 2embed.org have ads? Like overlay and video ads

It's doesn't have many ads like other providers and have more server. @BeamlakAschalew

**Comment by BeamlakAschalew** [comment]
> > Doesn't 2embed.org have ads? Like overlay and video ads
> 
> It's doesn't have many ads like other providers and have more server. @BeamlakAschalew 

Okay add it as another StreamListWidget()

**Comment by OshekharO** [comment]
> > > Doesn't 2embed.org have ads? Like overlay and video ads
> > 
> > 
> > It's doesn't have many ads like other providers and have more server. @BeamlakAschalew
> 
> Okay add it as another StreamListWidget() Don't override 'Stream one'

I am overwriting it because it contains all the server of 2embed.to and also additional servers. @OshekharO

**Comment by OshekharO** [comment]
Merge this

**Pull request merged**
